apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-works
spec:
  containers:
  - name: nginx-container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep"]
    args: ["300"]
